FROM python:3.12-bookworm

COPY ./requirements.txt ./requirements.txt
COPY ./requirements.extras.txt ./requirements.extras.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.extras.txt

COPY ./alembic ./alembic
COPY ./alembic.ini ./alembic.ini
COPY ./src ./src
COPY ./public/ ./public
COPY ./prometheus/ ./prometheus
COPY ./grafana/ ./grafana
COPY ./loki/ ./loki

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
