[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # isort
    "I",
]
# ignore = ["F401"]

[tool.bandit]
exclude_dirs = ["./src/__pycache__/", ".ruff_cache", ".venv", ".venv_linux"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
