"""Add_sla_breach_per_finding_name_08

Revision ID: 163a58a62416
Revises: ee281ad6c28f
Create Date: 2025-10-15 14:52:12.212925

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "163a58a62416"
down_revision: Union[str, None] = "ee281ad6c28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("bCritical_fn", sa.Integer(), nullable=True))
    op.add_column("log", sa.Column("bHigh_fn", sa.Integer(), nullable=True))
    op.add_column("log", sa.Column("bMedium_fn", sa.Integer(), nullable=True))
    op.add_column("log", sa.Column("bLow_fn", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log", "bLow_fn")
    op.drop_column("log", "bMedium_fn")
    op.drop_column("log", "bHigh_fn")
    op.drop_column("log", "bCritical_fn")
    # ### end Alembic commands ###
