"""Update_Finding_Index_06

Revision ID: 4dd4742a1a86
Revises: e01930917ca3
Create Date: 2025-10-07 12:03:15.255127

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd4742a1a86"
down_revision: Union[str, None] = "e01930917ca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_unique_finding_except_closed",
        table_name="finding",
        postgresql_where="(((status)::text <> 'CLOSED'::text) OR ((status)::text <> 'PASSED'::text))",  # noqa: E501
    )
    op.create_index(
        "uix_unique_finding_except_closed",
        "finding",
        ["finding_name_id", "host", "port", "plugin_id", "product_id", "label"],
        unique=True,
        postgresql_where=sa.text("status != 'CLOSED' OR status != 'PASSED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uix_unique_finding_except_closed",
        table_name="finding",
        postgresql_where=sa.text("status != 'CLOSED' OR status != 'PASSED'"),
    )
    op.create_index(
        "uix_unique_finding_except_closed",
        "finding",
        ["finding_name_id", "host", "port", "plugin_id", "product_id"],
        unique=True,
        postgresql_where="(((status)::text <> 'CLOSED'::text) OR ((status)::text <> 'PASSED'::text))",  # noqa: E501
    )
    # ### end Alembic commands ###
