"""ADD_LLM_CONFIG_02

Revision ID: b6d61ecf3d59
Revises: bbcfd4ec42a8
Create Date: 2025-08-22 16:21:19.883833

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6d61ecf3d59"
down_revision: Union[str, None] = "bbcfd4ec42a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_config", sa.Column("llm_url", sa.String(), nullable=True))
    op.add_column("global_config", sa.Column("llm_api_key", sa.String(), nullable=True))
    op.add_column("global_config", sa.Column("llm_model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_config", "llm_model")
    op.drop_column("global_config", "llm_api_key")
    op.drop_column("global_config", "llm_url")
    # ### end Alembic commands ###
