"""ADD_SMTP_TLS_05

Revision ID: e01930917ca3
Revises: 0c8ff4fe7797
Create Date: 2025-09-19 11:24:30.251146

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e01930917ca3"
down_revision: Union[str, None] = "0c8ff4fe7797"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "global_config",
        sa.Column("smtp_tls", sa.Boolean(), server_default="t", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_config", "smtp_tls")
    # ### end Alembic commands ###
